### ISSUE TITLE
Aggiunta di virtual envirovment

### ISSUE THREAD

**Issue by Angelorom** [CostaMart/ing-soft2#11]
Mettete la cazzo di virtual envirovment perché così si settano le dipendenze

**Comment by CostaMart** [comment]
Mica metti tutto il Venv su git, ho messo il requirements, basta che Ve le prendete da lì. È come voler caricare la VM Java ad ogni commit

**Comment by CostaMart** [comment]
Fate cosi: 
- prendete il requirements che sta lì e installatevi le dipdenze da dentro al file
- ora avete le dipendenze nuove + le vostre vecchie (fatelo in un Venv se no avrete tutte le dipendenze da quando avete iniziato ad usare Python)
- fate `pip freeze > requirements.txt` nella directory dove avete il requirements preferibilmente così lo sovrascrive
- ora avete un requirements aggiornato anche con le dipendenze vostre
- pushatelo maledetti

**Comment by Angelorom** [comment]
Allora ho capito dobbiamo prima creare un ambiente virtuale in locale e poi dire a git di non aggiungerlo mettendolo nel file gitignore, una volta attivato l'ambiente virtuale si installano le dipendenze facendo:
pip install -r requirement.txt 
In seguito ogni volta che si installa una nuova dipendenza per aggiornare questo file:
pip freeze > requirement.txt 
E poi lo pushare normalmente su github

**Comment by CostaMart** [comment]
Esatto, nel mio caso non ho fatto nemmeno git ignore, ho semplicemente creato il Venv nella cartella subito esterna al progetto.
Tanto vsc lo rileva, e se non lo rilevava basta andare nella cartella source con il CMD e fare activate
