### ISSUE TITLE
Bug Pulsante "Start Analysis

### ISSUE THREAD

**Issue by DarkHole43** [CostaMart/ing-soft2#31]
Quando si fa la prima analisi delle metriche , se si vuole cambiare classe i vecchi grafici rimangono nella pagina e si copre completamente la schermata di selezione

**Comment by Angelorom** [comment]
In realtà quei grafici sono proprio a caso non sono collegati alle classi, l'unica cosa è che devo fare in modo che quando viene ripetuto il tocco del bottone, allora devo far sparire quello di prima e poi lo ricreo

**Comment by DarkHole43** [comment]
sisi lo avevo capito, cerca di cancellare i grafici prima allora quando clicchi la nuova classe e fai l'analisi

**Comment by Angelorom** [comment]
Vedi che l'ho sistemato adesso guardati la lezione ahahah
